package com.eduhern.dbquiz.database;

import java.sql.SQLException;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.util.Log;

import com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper;
import com.j256.ormlite.dao.RuntimeExceptionDao;
import com.j256.ormlite.support.ConnectionSource;
import com.j256.ormlite.table.TableUtils;
import com.eduhern.dbquiz.R;
import com.eduhern.dbquiz.models.*;


public class DatabaseHelper extends OrmLiteSqliteOpenHelper {

	private static final String DATABASE_NAME = "dbquiz.db";
	private static final int DATABASE_VERSION = 33;

	private RuntimeExceptionDao<Pregunta, Integer> preguntaDAO = null;
	private RuntimeExceptionDao<Respuesta, Integer> respuestaDAO = null;
	private RuntimeExceptionDao<Categoria, Integer> categoriaDAO = null;


	public DatabaseHelper(final Context context) {
		super(context, DATABASE_NAME, null, DATABASE_VERSION,
				R.raw.ormlite_config);
		inserciones();
	}
	

	@Override
	public void onCreate(final SQLiteDatabase db,
			final ConnectionSource connectionSource) {
		try {
			TableUtils.createTable(connectionSource, Pregunta.class);
			TableUtils.createTable(connectionSource, Respuesta.class);
			TableUtils.createTable(connectionSource, Categoria.class);
		} catch (final SQLException e) {
			Log.e(DatabaseHelper.class.getName(), "Can't create database", e);
			throw new RuntimeException(e);
		}
	}

	@Override
	public void onUpgrade(final SQLiteDatabase db,
			final ConnectionSource connectionSource, final int oldVersion,
			final int newVersion) {
		try {
			TableUtils.dropTable(connectionSource, Pregunta.class, true);
			TableUtils.dropTable(connectionSource, Respuesta.class, true);
			TableUtils.dropTable(connectionSource, Categoria.class, true);

			onCreate(db, connectionSource);

		} catch (final java.sql.SQLException e) {
			Log.e(DatabaseHelper.class.getName(), "Can't drop databases", e);
			throw new RuntimeException(e);
		}
	}

	public RuntimeExceptionDao<Pregunta, Integer> getPreguntaDAO() {
		if (preguntaDAO == null) {
			preguntaDAO = getRuntimeExceptionDao(Pregunta.class);
		}
		return preguntaDAO;
	}

	public RuntimeExceptionDao<Respuesta, Integer> getRespuestaDAO() {
		if (respuestaDAO == null) {
			respuestaDAO = getRuntimeExceptionDao(Respuesta.class);
		}
		return respuestaDAO;
	}

	public RuntimeExceptionDao<Categoria, Integer> getCategoriaDAO() {
		if (categoriaDAO == null) {
			categoriaDAO = getRuntimeExceptionDao(Categoria.class);
		}
		return categoriaDAO;
	}
	
	private void inserciones(){
		Categoria geografia = new Categoria(1, "Geografía", "imagen_geografia", "Preguntas realacionadas con los distintos lugares de la partícular tierra y universo que envuelve a la obra de Toriyama y la Toei Animation");
	    Categoria ciencia = new Categoria(2, "Ciencia, Tecnología y Videojuegos", "imagen_ciencias", "Aparecerán preguntas vinculadas a distintos videojuegos relacionados con la serie, así como referencias a la propia tecnología utilizada en el Dragon World");
	    Categoria arte = new Categoria(3, "Arte, literatura y cine", "imagen_literatura", "Se tratarán preguntas sobre el propio manga creado por Toriyama, así como sus distintos libros de arte publicados en paralelo. También aparecerán aquí las cuestiones en relación a la filmografía de Dragon Ball creada por la Toei");
	    Categoria torneos = new Categoria(4, "Torneos y técnicas", "imagen_deportes", "¿Cuánto sabes sobre los torneos de artes marciales celebrados a lo largo de Dragon Ball? ¿Conoces las técnicas desarrolladas por los distintos personajes?");
	    Categoria dragon = new Categoria(5, "Dragon World", "imagen_espectaculos", "¿Te sabes el nombre de todos los personajes de Dragon Ball (tanto canónicos como no)? Quizás te sorprenda lo que puedas descubrir al adentrarte en las distintas relaciones entre ellos");
	    Categoria historia = new Categoria(6, "Historia", "imagen_historia", "Si conoces la cronología oficial creada para el Dragon Ball más canónico no tendrás ningún problema, sin embargo, ¿qué me dices de la historia real? ¿sabes cuándo han sucedido los estrenos y acontecimientos más importantes de la historia de Dragon Ball?");
	    
		this.getCategoriaDAO().create(geografia);
		this.getCategoriaDAO().create(ciencia);
		this.getCategoriaDAO().create(arte);
		this.getCategoriaDAO().create(torneos);
		this.getCategoriaDAO().create(dragon);
		this.getCategoriaDAO().create(historia);

		Pregunta pregunta1 = new Pregunta(1, "¿Cuál es el nombre de estos tres famosos villanos?", "imagen1", dragon, 1);
		Pregunta pregunta2 = new Pregunta(2, "¿Cuál es el nombre de este famoso personaje?", "imagen2", dragon, 1);
		Pregunta pregunta3 = new Pregunta(3, "¿Cómo se llama el personaje?", "imagen3", dragon, 1);
		Pregunta pregunta4 = new Pregunta(4, "¿Cuál es el nombre de este androide de base humana creado por el Dr. Gero?", "imagen4", dragon, 1);
		Pregunta pregunta5 = new Pregunta(5, "Fue el segundo maestro de Goku, ¿a qué nombre responde?", "imagen5", dragon, 1);
		Pregunta pregunta6 = new Pregunta(6, "¿En qué año se empezó a emitir la serie de animación que continuaba de forma canónica el manga de Toriyama?", "imagen6", historia, 2);
		Pregunta pregunta7 = new Pregunta(7, "¿Cuál es el título del primer tankobon del manga de Dragon Ball?", "imagen7", arte, 1);
		Pregunta pregunta8 = new Pregunta(8, "¿En qué año se estrenó el film de Dragon Ball 'Saikyo e no michi'?", "imagen8", arte, 2);
		Pregunta pregunta9 = new Pregunta(9, "¿Cómo se llama el hermando de Freezer?", "imagen9", dragon, 1);
		Pregunta pregunta10 = new Pregunta(10, "¿Cuál es el nombre de estos dos personajes del film de 2013 Dragon Ball Z 'Battle of Gods'?", "imagen10", dragon, 2);
		Pregunta pregunta11 = new Pregunta(11, "¿Para qué sirve el objeto de la fotografía?", "imagen11", ciencia, 1);
		Pregunta pregunta12 = new Pregunta(12, "¿Para qué sirve el objeto de la fotografía?", "imagen12", ciencia, 1);
		Pregunta pregunta13 = new Pregunta(13, "¿En qué plataforma podemos disfrutar del juego Dragon Ball Z 'Buyu Retsuden'?", "imagen13", ciencia, 1);
		Pregunta pregunta14 = new Pregunta(14, "¿Cuál era el principal poder del personaje de la imagen?", "imagen14", ciencia, 1);
		Pregunta pregunta15 = new Pregunta(15, "¿En qué capítulo de Dragon Ball GT alcanza Goku el estado de SSJ3 siendo un niño?", "imagen15", historia, 2);
		Pregunta pregunta16 = new Pregunta(16, "¿Qué parentesco comparte el personaje de la fotografía con Goku (Kakarotto)?", "imagen16", historia, 1);
		Pregunta pregunta17 = new Pregunta(17, "Goku adulto en DBGT convertido en SSJ, ¿es posible?", "imagen17", ciencia, 2);
		Pregunta pregunta18 = new Pregunta(18, "¿Qué videojuego es el que se corresponde con el de la imagen?", "imagen18", ciencia, 2);
		Pregunta pregunta19 = new Pregunta(19, "¿Cómo se llama el curioso personaje de la fotografía?", "imagen19", dragon, 2);
		Pregunta pregunta20 = new Pregunta(20, "¿Cuál es el nombre del guardian de la puerta del otro mundo?", "imagen20", dragon, 1);
		Pregunta pregunta21 = new Pregunta(21, "¿A qué se debe el aspecto que presenta Cooler en esta imagen?", "imagen21", ciencia, 2);
		Pregunta pregunta22 = new Pregunta(22, "¿Cómo se llama la novia de Son Gohan?", "imagen22", dragon, 1);
		Pregunta pregunta23 = new Pregunta(23, "¿En qué edición del Tenkaichi Budokai participó Punta, el personaje de la imagen?", "imagen23", torneos, 2);
		Pregunta pregunta24 = new Pregunta(24, "¿Cuál es el nombre del principe de los saiyans?", "imagen24", dragon, 1);
		Pregunta pregunta25 = new Pregunta(25, "¿En qué fase se encuentra Freezer en esta monstruosa forma?", "imagen25", ciencia, 1);
		Pregunta pregunta26 = new Pregunta(26, "¿De qué dos luchadores es fusión este personaje?", "imagen26", ciencia, 1);
		Pregunta pregunta27 = new Pregunta(27, "¿Por qué personaje es poseído Vegeta en Dragon Ball GT?", "imagen27", ciencia, 1);
		Pregunta pregunta28 = new Pregunta(28, "¿Cuántas veces muere y resucita Chaoz en el manga?", "imagen28", historia, 1);
		Pregunta pregunta29 = new Pregunta(29, "¿Cómo se llama esta muchacha?", "imagen29", ciencia, 1);
		Pregunta pregunta30 = new Pregunta(30, "¿Para qué plataforma estuvo disponible el juego 'Dragon Ball Z: SAGAS'?", "imagen30", ciencia, 2);
		Pregunta pregunta31 = new Pregunta(31, "¿Cómo se llama este androide completamente artificial?", "imagen31", dragon, 1);
		Pregunta pregunta32 = new Pregunta(32, "¿Y éste quién es?", "imagen32", dragon, 1);
		Pregunta pregunta33 = new Pregunta(33, "¿A quién tenemos aquí?", "imagen33", dragon, 1);
		Pregunta pregunta34 = new Pregunta(34, "¿Dónde esconde Bulma el diamante de la fotografía?", "imagen34", historia, 2);
		Pregunta pregunta35 = new Pregunta(35, "¿Qué deseo pidió Piccolo Daimaoh al dragon Shenron?", "imagen35", historia, 1);
		Pregunta pregunta36 = new Pregunta(36, "¿Cómo se llama este personaje de tres ojos?", "imagen36", dragon, 1);
		Pregunta pregunta37 = new Pregunta(37, "¿Contra qué enemigo se transforma Goku por primera vez en SSJ en Dragon Ball GT?", "imagen37", historia, 2);
		Pregunta pregunta38 = new Pregunta(38, "¿Cómo se llama este importante personaje del ejército de Freezer?", "imagen38", dragon, 1);
		Pregunta pregunta39 = new Pregunta(39, "Si este personaje no es Freezer, ¿de quién se trata?", "imagen39", dragon, 2);
		Pregunta pregunta40 = new Pregunta(40, "¿Qué parentesco comparte este personaje con Freezer?", "imagen40", dragon, 2);
		Pregunta pregunta41 = new Pregunta(41, "¿Cómo se llama este importante personaje del ejército de Freezer?", "imagen41", dragon, 1);
		Pregunta pregunta42 = new Pregunta(42, "¿Cuál es el nombre de este dragón maligno?", "imagen42", dragon, 2);
		Pregunta pregunta43 = new Pregunta(43, "¿Cómo se llama este poderoso enemigo?", "imagen43", dragon, 1);																										
		Pregunta pregunta44 = new Pregunta(44, "¿El odio de que antigua civilización tiene acumulado Hatchiyack?", "imagen44", historia, 1);
		Pregunta pregunta45 = new Pregunta(45, "¿Cómo se llama este gracioso villano del manga Neko Majin Z?", "imagen45", dragon, 2);
		Pregunta pregunta46 = new Pregunta(46, "¿En qué episodio de Dragon Ball Z aparece el personaje de la imagen?", "imagen46", historia, 2);
		Pregunta pregunta47 = new Pregunta(47, "¿Comparte Turles algún vínculo familiar con Goku?", "imagen47", historia, 1);
		Pregunta pregunta48 = new Pregunta(48, "¿Cómo se llama el hermano de Vegeta?", "imagen48", dragon, 2);
		Pregunta pregunta49 = new Pregunta(49, "¿Cómo se llamaba C18 antes de ser convertida en cyborg?", "imagen49", historia, 1);
		Pregunta pregunta50 = new Pregunta(50, "¿Cuál es el nombre de este importantísimo personaje de Dragon Ball?", "imagen50", dragon, 1);
		Pregunta pregunta51 = new Pregunta(51, "¿Cómo se llama este personaje secundario?", "imagen51", dragon, 2);
		Pregunta pregunta52 = new Pregunta(52, "¿Quién es el personaje de la imagen?", "imagen52", dragon, 1);
		Pregunta pregunta53 = new Pregunta(53, "¿Cómo se titula este film de Dragon Ball?", "imagen53",  arte, 1);
		Pregunta pregunta54 = new Pregunta(54, "¿Cómo se titula este film de Dragon Ball?", "imagen54", arte, 1);
		Pregunta pregunta55 = new Pregunta(55, "¿Cómo se titula este film de Dragon Ball?", "imagen55", arte, 1);
		Pregunta pregunta56 = new Pregunta(56, "¿Cómo se titula este film de Dragon Ball Z?", "imagen56", arte, 1);
		Pregunta pregunta57 = new Pregunta(57, "¿Quién es la autora del manga Dragon Ball SD?", "imagen57", arte, 2);
		Pregunta pregunta58 = new Pregunta(58, "¿Cómo se titula este film de Dragon Ball Z?", "imagen58", arte, 1);
		Pregunta pregunta59 = new Pregunta(59, "¿Cómo se titula este film de Dragon Ball Z?", "imagen59", arte, 1);
		Pregunta pregunta60 = new Pregunta(60, "¿Cómo se titula este film de Dragon Ball Z?", "imagen60", arte, 2);
		Pregunta pregunta61 = new Pregunta(61, "¿Cómo se titula este film de Dragon Ball Z?", "imagen61", arte, 2);
		Pregunta pregunta62 = new Pregunta(62, "¿Cómo se titula este film de Dragon Ball Z?", "imagen62", arte, 1);
		Pregunta pregunta63 = new Pregunta(63, "¿Cómo se titula este film de Dragon Ball Z?", "imagen63", arte, 2);																															
		Pregunta pregunta64 = new Pregunta(64, "¿Cómo se titula este film de Dragon Ball Z?", "imagen64", arte, 2);
		Pregunta pregunta65 = new Pregunta(65, "¿Cómo se titula este film de Dragon Ball Z?", "imagen65", arte, 1);
		Pregunta pregunta66 = new Pregunta(66, "¿Cómo se titula este film de Dragon Ball Z?", "imagen66", arte, 1);
		Pregunta pregunta67 = new Pregunta(67, "¿Cómo se titula este film de Dragon Ball Z?", "imagen67", arte, 2);
		Pregunta pregunta68 = new Pregunta(68, "¿Cómo se titula este film de Dragon Ball Z?", "imagen68", arte, 2);
		Pregunta pregunta69 = new Pregunta(69, "¿Cuál es el videojuego de la imagen?", "imagen69", ciencia, 2);
		Pregunta pregunta70 = new Pregunta(70, "¿Cuál es el videojuego de la imagen?", "imagen70", ciencia, 2);
		Pregunta pregunta71 = new Pregunta(71, "¿Cuál es el videojuego de la imagen?", "imagen71", ciencia, 2);
		Pregunta pregunta72 = new Pregunta(72, "¿En qué edición del Tenkaichi Budokai participó Ran Fan?", "imagen72", torneos, 1);
		Pregunta pregunta73 = new Pregunta(73, "¿Sobre qué número está etiquetado este androide?", "imagen73", dragon, 1);																																
		Pregunta pregunta74 = new Pregunta(74, "¿A qué se dedicaba Cynthia, el personaje de la imagen?", "imagen74", historia, 2);
		Pregunta pregunta75 = new Pregunta(75, "¿Qué fusión está tras este personaje del manga/arcade Dragon Ball Heroes?", "imagen75", torneos, 1);
		Pregunta pregunta76 = new Pregunta(76, "¿Cómo se llama el protagonista de Dragon Ball?", "imagen76", dragon, 1);
		Pregunta pregunta77 = new Pregunta(77, "¿En qué lugar habita Enma, la anciana de la foto?", "imagen77", geografia, 2);
		Pregunta pregunta78 = new Pregunta(78, "¿Cómo se llama esta joven?", "imagen78", dragon, 1);
		Pregunta pregunta79 = new Pregunta(79, "¿Qué técnica está realizando Krilín en esta foto?", "imagen79", torneos, 1);
		Pregunta pregunta80 = new Pregunta(80, "Gotenks es la fusión de dos personajes, ¿quiénes?", "imagen80", torneos, 1);
		Pregunta pregunta81 = new Pregunta(81, "¿Qué opina Zarbon de su metamorfosis?", "imagen81", torneos, 1);
		Pregunta pregunta82 = new Pregunta(82, "¿Cómo se llama el personaje de la imagen?", "imagen82", dragon, 2);
		Pregunta pregunta83 = new Pregunta(83, "¿Qué rango tenía, dentro del ejército de la Red Ribbon, Violet?", "imagen83", historia, 1);	
		Pregunta pregunta84 = new Pregunta(84, "¿Cómo se llama esta saiyana pura perteneciente al escuadrón de Bardock?", "imagen84", dragon, 1);
		Pregunta pregunta85 = new Pregunta(85, "¿Cómo se llama este personaje?", "imagen85", dragon, 1);
		Pregunta pregunta86 = new Pregunta(86, "¿De qué dos personajes es fusión Vegetto?", "imagen86", torneos, 1);
		Pregunta pregunta87 = new Pregunta(87, "¿Para qué propósito está reuniendo Gokuh las bolas de dragón?", "imagen87", historia, 1);
		Pregunta pregunta88 = new Pregunta(88, "¿A qué nombre responde este personaje?", "imagen88", dragon, 1);
		Pregunta pregunta89 = new Pregunta(89, "¿En qué posición quedó Gokuh en el 23º Tenkaichi Budokai?", "imagen89", historia, 1);	
		
		this.getPreguntaDAO().create(pregunta1);
        this.getPreguntaDAO().create(pregunta2);
        this.getPreguntaDAO().create(pregunta3);
        this.getPreguntaDAO().create(pregunta4);
        this.getPreguntaDAO().create(pregunta5);
        this.getPreguntaDAO().create(pregunta6);
        this.getPreguntaDAO().create(pregunta7);
        this.getPreguntaDAO().create(pregunta8);
        this.getPreguntaDAO().create(pregunta9);
        this.getPreguntaDAO().create(pregunta10);
        this.getPreguntaDAO().create(pregunta11);
        this.getPreguntaDAO().create(pregunta12);
        this.getPreguntaDAO().create(pregunta13);
        this.getPreguntaDAO().create(pregunta14);
        this.getPreguntaDAO().create(pregunta15);
        this.getPreguntaDAO().create(pregunta16);
        this.getPreguntaDAO().create(pregunta17);
        this.getPreguntaDAO().create(pregunta18);
        this.getPreguntaDAO().create(pregunta19);
        this.getPreguntaDAO().create(pregunta20);
        this.getPreguntaDAO().create(pregunta21);
        this.getPreguntaDAO().create(pregunta22);
        this.getPreguntaDAO().create(pregunta23);
        this.getPreguntaDAO().create(pregunta24);
        this.getPreguntaDAO().create(pregunta25);
        this.getPreguntaDAO().create(pregunta26);
        this.getPreguntaDAO().create(pregunta27);
        this.getPreguntaDAO().create(pregunta28);
        this.getPreguntaDAO().create(pregunta29);
        this.getPreguntaDAO().create(pregunta30);
        this.getPreguntaDAO().create(pregunta31);
        this.getPreguntaDAO().create(pregunta32);
        this.getPreguntaDAO().create(pregunta33);
        this.getPreguntaDAO().create(pregunta34);
        this.getPreguntaDAO().create(pregunta35);
        this.getPreguntaDAO().create(pregunta36);
        this.getPreguntaDAO().create(pregunta37);
        this.getPreguntaDAO().create(pregunta38);
        this.getPreguntaDAO().create(pregunta39);
        this.getPreguntaDAO().create(pregunta40);
        this.getPreguntaDAO().create(pregunta41);
        this.getPreguntaDAO().create(pregunta42);
        this.getPreguntaDAO().create(pregunta43);
        this.getPreguntaDAO().create(pregunta44);
        this.getPreguntaDAO().create(pregunta45);
        this.getPreguntaDAO().create(pregunta46);
        this.getPreguntaDAO().create(pregunta47);
        this.getPreguntaDAO().create(pregunta48);
        this.getPreguntaDAO().create(pregunta49);
        this.getPreguntaDAO().create(pregunta50);
        this.getPreguntaDAO().create(pregunta51);
        this.getPreguntaDAO().create(pregunta52);
        this.getPreguntaDAO().create(pregunta53);
        this.getPreguntaDAO().create(pregunta54);
        this.getPreguntaDAO().create(pregunta55);
        this.getPreguntaDAO().create(pregunta56);
        this.getPreguntaDAO().create(pregunta57);
        this.getPreguntaDAO().create(pregunta58);
        this.getPreguntaDAO().create(pregunta59);
        this.getPreguntaDAO().create(pregunta60);
        this.getPreguntaDAO().create(pregunta61);
        this.getPreguntaDAO().create(pregunta62);
        this.getPreguntaDAO().create(pregunta63);
        this.getPreguntaDAO().create(pregunta64);
        this.getPreguntaDAO().create(pregunta65);
        this.getPreguntaDAO().create(pregunta66);
        this.getPreguntaDAO().create(pregunta67);
        this.getPreguntaDAO().create(pregunta68);
        this.getPreguntaDAO().create(pregunta69);
        this.getPreguntaDAO().create(pregunta70);
        this.getPreguntaDAO().create(pregunta71);
        this.getPreguntaDAO().create(pregunta72);
        this.getPreguntaDAO().create(pregunta73);
        this.getPreguntaDAO().create(pregunta74);
        this.getPreguntaDAO().create(pregunta75);
        this.getPreguntaDAO().create(pregunta76);
        this.getPreguntaDAO().create(pregunta77);
        this.getPreguntaDAO().create(pregunta78);
        this.getPreguntaDAO().create(pregunta79);
        this.getPreguntaDAO().create(pregunta80);
        this.getPreguntaDAO().create(pregunta81);
        this.getPreguntaDAO().create(pregunta82);
        this.getPreguntaDAO().create(pregunta83);
        this.getPreguntaDAO().create(pregunta84);
        this.getPreguntaDAO().create(pregunta85);
        this.getPreguntaDAO().create(pregunta86);
        this.getPreguntaDAO().create(pregunta87);
        this.getPreguntaDAO().create(pregunta88);
        this.getPreguntaDAO().create(pregunta89);

        this.getRespuestaDAO().create(new Respuesta(0, true, "Pilaf, Mai y Suu", pregunta1));
        this.getRespuestaDAO().create(new Respuesta(1, false, "Pilaf, Mai y Ginew", pregunta1));
        this.getRespuestaDAO().create(new Respuesta(2, false, "Vegeta, Mai y Zarbon", pregunta1));
        this.getRespuestaDAO().create(new Respuesta(3, false, "Dodoria, Kiwi y Zarbon", pregunta1));
        this.getRespuestaDAO().create(new Respuesta(4, false, "Cell", pregunta2));
        this.getRespuestaDAO().create(new Respuesta(5, false, "Super Bu", pregunta2));
        this.getRespuestaDAO().create(new Respuesta(6, true, "Mr Bu", pregunta2));
        this.getRespuestaDAO().create(new Respuesta(7, false, "Kid Bu", pregunta2));
		this.getRespuestaDAO().create(new Respuesta(8, false, "Ten Shin Han", pregunta3));
		this.getRespuestaDAO().create(new Respuesta(9, true, "Yamcha", pregunta3));
		this.getRespuestaDAO().create(new Respuesta(10, false, "Puar", pregunta3));
		this.getRespuestaDAO().create(new Respuesta(11, false, "Oolong", pregunta3));
		this.getRespuestaDAO().create(new Respuesta(12, false, "C17", pregunta4));
		this.getRespuestaDAO().create(new Respuesta(13, true, "C18", pregunta4));
		this.getRespuestaDAO().create(new Respuesta(14, false, "C19", pregunta4));
		this.getRespuestaDAO().create(new Respuesta(15, false, "C20", pregunta4));
		this.getRespuestaDAO().create(new Respuesta(16, false, "Gyumaoh", pregunta5));
		this.getRespuestaDAO().create(new Respuesta(17, false, "Youmaoh", pregunta5));
		this.getRespuestaDAO().create(new Respuesta(18, true, "Mutenroshi", pregunta5));
		this.getRespuestaDAO().create(new Respuesta(19, false, "Mutaito", pregunta5));
		this.getRespuestaDAO().create(new Respuesta(20, false, "1994", pregunta6));
		this.getRespuestaDAO().create(new Respuesta(21, false, "1995", pregunta6));
		this.getRespuestaDAO().create(new Respuesta(22, true, "1996", pregunta6));
		this.getRespuestaDAO().create(new Respuesta(23, false, "1997", pregunta6));
		this.getRespuestaDAO().create(new Respuesta(24, true, "Son Goku y sus amigos", pregunta7));
		this.getRespuestaDAO().create(new Respuesta(25, false, "El gran combate", pregunta7));
		this.getRespuestaDAO().create(new Respuesta(26, false, "¡Adelante Son Goku!", pregunta7));
		this.getRespuestaDAO().create(new Respuesta(27, false, "Un plan diabólico", pregunta7));
		this.getRespuestaDAO().create(new Respuesta(28, false, "1989", pregunta8));
		this.getRespuestaDAO().create(new Respuesta(29, false, "1990", pregunta8));
		this.getRespuestaDAO().create(new Respuesta(30, false, "1993", pregunta8));
		this.getRespuestaDAO().create(new Respuesta(31, true, "1996", pregunta8));
		this.getRespuestaDAO().create(new Respuesta(32, false, "Raditz", pregunta9));
		this.getRespuestaDAO().create(new Respuesta(33, false, "King Cold", pregunta9));
		this.getRespuestaDAO().create(new Respuesta(34, true, "Cooler", pregunta9));
		this.getRespuestaDAO().create(new Respuesta(35, false, "Broly", pregunta9));				
		this.getRespuestaDAO().create(new Respuesta(36, false, "Abo y Kado", pregunta10));
		this.getRespuestaDAO().create(new Respuesta(37, true, "Birusu y Wisu", pregunta10));
		this.getRespuestaDAO().create(new Respuesta(38, false, "Zarbón y Dodoria", pregunta10));
		this.getRespuestaDAO().create(new Respuesta(39, false, "Vegeta y Nappa", pregunta10));
		this.getRespuestaDAO().create(new Respuesta(40, false, "Todo aquel que lleva puesto el pendiente incrementa su fuerza.", pregunta11));
		this.getRespuestaDAO().create(new Respuesta(41, false, "Es meramente un elemento estético", pregunta11));
		this.getRespuestaDAO().create(new Respuesta(42, true, "Es un pendiente de los dioses kaio shin. Permite realizar una ancestral fusión", pregunta11));
		this.getRespuestaDAO().create(new Respuesta(43, false, "Es un simple reloj", pregunta12));
		this.getRespuestaDAO().create(new Respuesta(44, true, "Permite detectar las bolas de dragón", pregunta12));
		this.getRespuestaDAO().create(new Respuesta(45, false, "Permite localizar focos de ki", pregunta12));
		this.getRespuestaDAO().create(new Respuesta(46, false, "Es el nuevo smartphone de apple", pregunta12));
		this.getRespuestaDAO().create(new Respuesta(47, true, "Sega Megadrive / Genesis", pregunta13));
		this.getRespuestaDAO().create(new Respuesta(48, false, "Super nintendo / Famicom", pregunta13));
		this.getRespuestaDAO().create(new Respuesta(49, false, "Nintendo Game Boy", pregunta13));
		this.getRespuestaDAO().create(new Respuesta(50, false, "Neo Geo", pregunta13));
		this.getRespuestaDAO().create(new Respuesta(51, false, "Puede realizar el Kame Hame Ha", pregunta14));
		this.getRespuestaDAO().create(new Respuesta(52, true, "Tiene la capacidad de variar el tamaño de su cuerpo", pregunta14));
		this.getRespuestaDAO().create(new Respuesta(53, false, "Tiene poderes curativos", pregunta14));
		this.getRespuestaDAO().create(new Respuesta(54, false, "Ninguno, es un simple humano", pregunta14));
		this.getRespuestaDAO().create(new Respuesta(55, false, "Episodio 6", pregunta15));
		this.getRespuestaDAO().create(new Respuesta(56, false, "Episodio 25", pregunta15));
		this.getRespuestaDAO().create(new Respuesta(57, true, "Episodio 29", pregunta15));
		this.getRespuestaDAO().create(new Respuesta(58, false, "Episodio 33", pregunta15));
		this.getRespuestaDAO().create(new Respuesta(59, false, "Sobrino", pregunta16));
		this.getRespuestaDAO().create(new Respuesta(60, false, "Hijo", pregunta16));
		this.getRespuestaDAO().create(new Respuesta(61, false, "Hermano", pregunta16));
		this.getRespuestaDAO().create(new Respuesta(62, true, "Tataranieto", pregunta16));
		this.getRespuestaDAO().create(new Respuesta(63, false, "No, no lo es", pregunta17));
		this.getRespuestaDAO().create(new Respuesta(64, true, "Sí, aparece como personaje seleccionable en el Dragon Ball 'Final Bout' de PSX", pregunta17));
		this.getRespuestaDAO().create(new Respuesta(65, false, "Sí, en el primer capítulo de DBGT le podemos ver en este estado", pregunta17));
		this.getRespuestaDAO().create(new Respuesta(66, false, "Sí, en el último capítulo de DBGT le podemos ver en este estado", pregunta17));
		this.getRespuestaDAO().create(new Respuesta(67, false, "Dragon Ball: Final Bout", pregunta18));
		this.getRespuestaDAO().create(new Respuesta(68, true, "Dragon Ball: Revenge of King Piccolo", pregunta18));
		this.getRespuestaDAO().create(new Respuesta(69, false, "Dragon Ball: Advance adventure", pregunta18));
		this.getRespuestaDAO().create(new Respuesta(70, false, "Dragon Ball Z Budokai", pregunta18));
		this.getRespuestaDAO().create(new Respuesta(71, false, "Chichi", pregunta19));
		this.getRespuestaDAO().create(new Respuesta(72, false, "Marron", pregunta19));
		this.getRespuestaDAO().create(new Respuesta(73, true, "Grey", pregunta19));
		this.getRespuestaDAO().create(new Respuesta(74, false, "Snow", pregunta19));
		this.getRespuestaDAO().create(new Respuesta(75, false, "Kaioh Sama", pregunta20));
		this.getRespuestaDAO().create(new Respuesta(76, false, "Ro Kaioh Shin", pregunta20));
		this.getRespuestaDAO().create(new Respuesta(77, false, "Kibito", pregunta20));
		this.getRespuestaDAO().create(new Respuesta(78, true, "Enma Daioh", pregunta20));
        this.getRespuestaDAO().create(new Respuesta(79, true, "Se debe al comportamiento de asimilación de un microchip inteligente", pregunta21));
		this.getRespuestaDAO().create(new Respuesta(80, false, "Se debe a la reconstrucción de su cuerpo tras su enfrentamiento con Goku", pregunta21));
		this.getRespuestaDAO().create(new Respuesta(81, false, "Se debe a los arreglos que el Dr. Gero introdujo en su cuerpo", pregunta21));
		this.getRespuestaDAO().create(new Respuesta(82, false, "Bulma", pregunta22));
		this.getRespuestaDAO().create(new Respuesta(83, true, "Videl", pregunta22));
		this.getRespuestaDAO().create(new Respuesta(84, false, "Marron", pregunta22));
		this.getRespuestaDAO().create(new Respuesta(85, false, "Pasta", pregunta22));
		this.getRespuestaDAO().create(new Respuesta(86, false, "22º Tenkaichi Budokai", pregunta23));
		this.getRespuestaDAO().create(new Respuesta(87, false, "23º Tenkaichi Budokai", pregunta23));
		this.getRespuestaDAO().create(new Respuesta(88, false, "24º Tenkaichi Budokai", pregunta23));
		this.getRespuestaDAO().create(new Respuesta(89, true, "25º Tenkaichi Budokai", pregunta23));	        
		this.getRespuestaDAO().create(new Respuesta(90, false, "Nappa", pregunta24));
		this.getRespuestaDAO().create(new Respuesta(91, false, "Raditz", pregunta24));
		this.getRespuestaDAO().create(new Respuesta(92, true, "Vegeta", pregunta24));
		this.getRespuestaDAO().create(new Respuesta(93, false, "Bardock", pregunta24));
		this.getRespuestaDAO().create(new Respuesta(94, true, "Tercera fase", pregunta25));
		this.getRespuestaDAO().create(new Respuesta(95, false, "Segunda fase", pregunta25));
		this.getRespuestaDAO().create(new Respuesta(96, false, "Cuarta fase", pregunta25));
		this.getRespuestaDAO().create(new Respuesta(97, false, "Primera fase", pregunta25));
		this.getRespuestaDAO().create(new Respuesta(98, false, "Goku + Vegeta", pregunta26));
		this.getRespuestaDAO().create(new Respuesta(99, true, "Uub + Buu", pregunta26));
		this.getRespuestaDAO().create(new Respuesta(100, false, "Baby + Vegeta", pregunta26));
		this.getRespuestaDAO().create(new Respuesta(101, false, "Kibito + Kaioh Shin", pregunta26));
		this.getRespuestaDAO().create(new Respuesta(102, false, "Super C17", pregunta27));
		this.getRespuestaDAO().create(new Respuesta(103, false, "Redic", pregunta27));
		this.getRespuestaDAO().create(new Respuesta(104, true, "Baby", pregunta27));
		this.getRespuestaDAO().create(new Respuesta(105, false, "Dr. Myu", pregunta27));
		this.getRespuestaDAO().create(new Respuesta(106, false, "Dos", pregunta28));
		this.getRespuestaDAO().create(new Respuesta(107, false, "Una", pregunta28));
		this.getRespuestaDAO().create(new Respuesta(108, false, "Cuatro", pregunta28));
		this.getRespuestaDAO().create(new Respuesta(109, true, "Tres", pregunta28));
		this.getRespuestaDAO().create(new Respuesta(110, true, "Pan", pregunta29));
		this.getRespuestaDAO().create(new Respuesta(111, false, "Bra", pregunta29));
		this.getRespuestaDAO().create(new Respuesta(112, false, "Videl", pregunta29));
		this.getRespuestaDAO().create(new Respuesta(113, false, "Marron", pregunta29));
		this.getRespuestaDAO().create(new Respuesta(114, true, "Xbox, Play Station 2 y Game Cube", pregunta30));
		this.getRespuestaDAO().create(new Respuesta(115, false, "Xbox 360, Play Station 3 y Wii", pregunta30));
		this.getRespuestaDAO().create(new Respuesta(116, false, "Play Station 2 y Wii", pregunta30));
		this.getRespuestaDAO().create(new Respuesta(117, false, "Game Cube y Xbox", pregunta30));
		this.getRespuestaDAO().create(new Respuesta(118, false, "C13", pregunta31));
		this.getRespuestaDAO().create(new Respuesta(119, true, "C16", pregunta31));
		this.getRespuestaDAO().create(new Respuesta(120, false, "C15", pregunta31));
		this.getRespuestaDAO().create(new Respuesta(121, false, "C14", pregunta31));
		this.getRespuestaDAO().create(new Respuesta(122, false, "Muchi Mochi", pregunta32));
		this.getRespuestaDAO().create(new Respuesta(123, true, "Loud", pregunta32));
		this.getRespuestaDAO().create(new Respuesta(124, false, "Redic", pregunta32));
		this.getRespuestaDAO().create(new Respuesta(125, false, "Sonpara", pregunta32));
		this.getRespuestaDAO().create(new Respuesta(126, false, "Gyumaoh", pregunta33));
		this.getRespuestaDAO().create(new Respuesta(127, false, "Kame Senin", pregunta33));
		this.getRespuestaDAO().create(new Respuesta(128, true, "Son Gohan Ojichan", pregunta33));
		this.getRespuestaDAO().create(new Respuesta(129, false, "Tsuru Senin", pregunta33));
		this.getRespuestaDAO().create(new Respuesta(130, false, "Dentro de su mochila", pregunta34));
		this.getRespuestaDAO().create(new Respuesta(131, false, "En ningún momento lo lleva escondido", pregunta34));
		this.getRespuestaDAO().create(new Respuesta(132, true, "Se lo mete en la entrepierna", pregunta34));
		this.getRespuestaDAO().create(new Respuesta(133, false, "Lo lleva metido en el escote", pregunta34));
		this.getRespuestaDAO().create(new Respuesta(134, false, "La vida eterna", pregunta35));
		this.getRespuestaDAO().create(new Respuesta(135, false, "Reinar en el mundo", pregunta35));
		this.getRespuestaDAO().create(new Respuesta(136, false, "Reinar en el universo", pregunta35));
		this.getRespuestaDAO().create(new Respuesta(137, true, "Volver a recuperar su juventud", pregunta35));
		this.getRespuestaDAO().create(new Respuesta(138, false, "Tao Pai Pai", pregunta36));
		this.getRespuestaDAO().create(new Respuesta(139, false, "Chaoz", pregunta36));
		this.getRespuestaDAO().create(new Respuesta(140, false, "Tsuru Senin", pregunta36));
		this.getRespuestaDAO().create(new Respuesta(141, true, "Ten Shin Han", pregunta36));
		this.getRespuestaDAO().create(new Respuesta(142, true, "Redic", pregunta37));
		this.getRespuestaDAO().create(new Respuesta(143, false, "Don Kear", pregunta37));
		this.getRespuestaDAO().create(new Respuesta(144, false, "Pilaf", pregunta37));
		this.getRespuestaDAO().create(new Respuesta(145, false, "Muchi Mochi", pregunta37));
		this.getRespuestaDAO().create(new Respuesta(146, true, "Zarbon", pregunta38));
		this.getRespuestaDAO().create(new Respuesta(147, false, "Dodoria", pregunta38));
		this.getRespuestaDAO().create(new Respuesta(148, false, "Ginew", pregunta38));
		this.getRespuestaDAO().create(new Respuesta(149, false, "Reecom", pregunta38));
		this.getRespuestaDAO().create(new Respuesta(150, false, "Kuriza", pregunta39));
		this.getRespuestaDAO().create(new Respuesta(151, true, "Chilled", pregunta39));
		this.getRespuestaDAO().create(new Respuesta(152, false, "Cooler", pregunta39));
		this.getRespuestaDAO().create(new Respuesta(153, false, "King Cold", pregunta39));
		this.getRespuestaDAO().create(new Respuesta(154, false, "Es su hermano pequeño", pregunta40));
		this.getRespuestaDAO().create(new Respuesta(155, true, "Es su hijo", pregunta40));
		this.getRespuestaDAO().create(new Respuesta(156, false, "Es su sobrino", pregunta40));
		this.getRespuestaDAO().create(new Respuesta(157, false, "No es familia suya", pregunta40));
		this.getRespuestaDAO().create(new Respuesta(158, false, "Zarbon", pregunta41));
		this.getRespuestaDAO().create(new Respuesta(159, false, "Ghourd", pregunta41));
		this.getRespuestaDAO().create(new Respuesta(160, true, "Dodoria", pregunta41));
		this.getRespuestaDAO().create(new Respuesta(161, false, "Burter", pregunta41));
		this.getRespuestaDAO().create(new Respuesta(162, false, "Chih Shinron", pregunta42));
		this.getRespuestaDAO().create(new Respuesta(163, false, "Suu Shinron", pregunta42));
		this.getRespuestaDAO().create(new Respuesta(164, true, "Ryan Shinron", pregunta42));
		this.getRespuestaDAO().create(new Respuesta(165, false, "San Shinron", pregunta42));
		this.getRespuestaDAO().create(new Respuesta(166, false, "Vegeta", pregunta43));
		this.getRespuestaDAO().create(new Respuesta(167, false, "Baby", pregunta43));
		this.getRespuestaDAO().create(new Respuesta(168, false, "Majin Buu", pregunta43));
		this.getRespuestaDAO().create(new Respuesta(169, true, "Vegeta-Baby", pregunta43));
		this.getRespuestaDAO().create(new Respuesta(170, false, "Saiyanos", pregunta44));
		this.getRespuestaDAO().create(new Respuesta(171, false, "Namekianos", pregunta44));
		this.getRespuestaDAO().create(new Respuesta(172, false, "Terrícolas", pregunta44));
		this.getRespuestaDAO().create(new Respuesta(173, true, "Tsufurs", pregunta44));
		this.getRespuestaDAO().create(new Respuesta(174, true, "Kuriza", pregunta45));
		this.getRespuestaDAO().create(new Respuesta(175, false, "Neko Majin", pregunta45));
		this.getRespuestaDAO().create(new Respuesta(176, false, "Onio", pregunta45));
		this.getRespuestaDAO().create(new Respuesta(177, false, "Thunderbolt", pregunta45));
		this.getRespuestaDAO().create(new Respuesta(178, true, "Capítulo 54", pregunta46));
		this.getRespuestaDAO().create(new Respuesta(179, false, "Capítulo 55", pregunta46));
		this.getRespuestaDAO().create(new Respuesta(180, false, "Capítulo 56", pregunta46));
		this.getRespuestaDAO().create(new Respuesta(181, false, "Capítulo 57", pregunta46));
		this.getRespuestaDAO().create(new Respuesta(182, true, "No", pregunta47));
		this.getRespuestaDAO().create(new Respuesta(183, false, "Sí", pregunta47));
		this.getRespuestaDAO().create(new Respuesta(184, false, "Raditz", pregunta48));
		this.getRespuestaDAO().create(new Respuesta(185, true, "Tarble", pregunta48));
		this.getRespuestaDAO().create(new Respuesta(186, false, "Turles", pregunta48));
		this.getRespuestaDAO().create(new Respuesta(187, false, "Broly", pregunta48));
		this.getRespuestaDAO().create(new Respuesta(188, false, "Marron", pregunta49));
		this.getRespuestaDAO().create(new Respuesta(189, false, "Misato", pregunta49));
		this.getRespuestaDAO().create(new Respuesta(190, false, "Ritsuko", pregunta49));
		this.getRespuestaDAO().create(new Respuesta(191, true, "Todas las respuestas anteriores son falsas", pregunta49));
		this.getRespuestaDAO().create(new Respuesta(184, false, "Chichi", pregunta50));
		this.getRespuestaDAO().create(new Respuesta(185, false, "Lunch", pregunta50));
		this.getRespuestaDAO().create(new Respuesta(186, true, "Bulma", pregunta50));
		this.getRespuestaDAO().create(new Respuesta(187, false, "Bra", pregunta50));
		this.getRespuestaDAO().create(new Respuesta(188, false, "Lakasei", pregunta51));
		this.getRespuestaDAO().create(new Respuesta(189, false, "Cacao", pregunta51));
		this.getRespuestaDAO().create(new Respuesta(190, true, "Daizu", pregunta51));
		this.getRespuestaDAO().create(new Respuesta(191, false, "Turles", pregunta51));
		this.getRespuestaDAO().create(new Respuesta(192, false, "Dende", pregunta52));
		this.getRespuestaDAO().create(new Respuesta(193, false, "Kargo", pregunta52));
		this.getRespuestaDAO().create(new Respuesta(194, false, "Slug", pregunta52));
		this.getRespuestaDAO().create(new Respuesta(195, true, "Piccolo", pregunta52));
		this.getRespuestaDAO().create(new Respuesta(196, false, "El camino hacia el más fuerte", pregunta53));
		this.getRespuestaDAO().create(new Respuesta(197, false, "Aventura Mística", pregunta53));
		this.getRespuestaDAO().create(new Respuesta(198, false, "La Bella Durmiente en el Castillo del Mal", pregunta53));
		this.getRespuestaDAO().create(new Respuesta(199, true, "La Leyenda del dragón Shenlong", pregunta53));
		this.getRespuestaDAO().create(new Respuesta(200, true, "La Bella Durmiente en el Castillo del Mal", pregunta54));
		this.getRespuestaDAO().create(new Respuesta(201, false, "La Leyenda del dragón Shenlong", pregunta54));
		this.getRespuestaDAO().create(new Respuesta(202, false, "El camino hacia el más fuerte", pregunta54));
		this.getRespuestaDAO().create(new Respuesta(203, false, "Aventura Mística", pregunta54));
		this.getRespuestaDAO().create(new Respuesta(204, true, "Aventura Mística", pregunta55));
		this.getRespuestaDAO().create(new Respuesta(205, false, "La Bella Durmiente en el Castillo del Mal", pregunta55));
		this.getRespuestaDAO().create(new Respuesta(206, false, "El camino hacia el más fuerte", pregunta55));
		this.getRespuestaDAO().create(new Respuesta(207, false, "La Leyenda del dragón Shenlong", pregunta55));
		this.getRespuestaDAO().create(new Respuesta(208, false, "¡¡Arde!! Super batalla feroz, extrema y ardiente", pregunta56));
		this.getRespuestaDAO().create(new Respuesta(209, true, "El hombre más fuerte de este mundo", pregunta56));
		this.getRespuestaDAO().create(new Respuesta(210, false, "¡¡La galaxia está en peligro!! Un guerrero Súper increíble", pregunta56));
		this.getRespuestaDAO().create(new Respuesta(211, false, "¡¡Batalla extrema!! Los Tres Grandes Super Saiyajin", pregunta56));
		this.getRespuestaDAO().create(new Respuesta(212, false, "Chica Umino", pregunta57));
		this.getRespuestaDAO().create(new Respuesta(213, true, "Naho Ooishi", pregunta57));
		this.getRespuestaDAO().create(new Respuesta(214, false, "Yukari Ichijo", pregunta57));
		this.getRespuestaDAO().create(new Respuesta(215, false, "Ai Yazawa", pregunta57));
		this.getRespuestaDAO().create(new Respuesta(216, false, "¡¡La galaxia está en peligro!! Un guerrero Súper increíble", pregunta58));
		this.getRespuestaDAO().create(new Respuesta(217, false, "El hombre más fuerte de este mundo", pregunta58));
		this.getRespuestaDAO().create(new Respuesta(218, true, "Super batalla decisiva por el planeta Tierra", pregunta58));
		this.getRespuestaDAO().create(new Respuesta(219, false, "¡¡Batalla extrema!! Los Tres Grandes Super Saiyajin", pregunta58));
		this.getRespuestaDAO().create(new Respuesta(220, false, "¡¡Arde!! Super batalla feroz, extrema y ardiente", pregunta59));
		this.getRespuestaDAO().create(new Respuesta(221, false, "¡Los dos en peligro! Los Súper guerreros nunca duermen", pregunta59));
		this.getRespuestaDAO().create(new Respuesta(222, true, "Goku es un Super Saiyajin", pregunta59));
		this.getRespuestaDAO().create(new Respuesta(223, false, "¡¡La galaxia está en peligro!! Un guerrero Súper increíble", pregunta59));
		this.getRespuestaDAO().create(new Respuesta(224, false, "¡Explota el golpe del dragón! Si Goku no lo logra ¿quién lo hará?", pregunta60));
		this.getRespuestaDAO().create(new Respuesta(225, false, "El hombre más fuerte de este mundo", pregunta60));
		this.getRespuestaDAO().create(new Respuesta(226, false, "¡Los dos en peligro! Los Súper guerreros nunca duermen", pregunta60));
		this.getRespuestaDAO().create(new Respuesta(227, true, "Los increíbles más poderosos contra el más poderoso", pregunta60));
		this.getRespuestaDAO().create(new Respuesta(228, false, "¡Los Super guerreros vencen! La victoria será para mi", pregunta61));
		this.getRespuestaDAO().create(new Respuesta(229, false, "¡Explota el golpe del dragón! Si Goku no lo logra ¿quién lo hará?", pregunta61));
		this.getRespuestaDAO().create(new Respuesta(230, false, "El hombre más fuerte de este mundo", pregunta61));
		this.getRespuestaDAO().create(new Respuesta(231, true, "¡¡Choque!! Guerreros de 10.000.000.000 poderes", pregunta61));
		this.getRespuestaDAO().create(new Respuesta(232, true, "¡¡Batalla extrema!! Los Tres Grandes Super Saiyajin", pregunta62));
		this.getRespuestaDAO().create(new Respuesta(233, false, "¡El renacer de la fusión! Goku y Vegeta", pregunta62));
		this.getRespuestaDAO().create(new Respuesta(234, false, "¡Los Super guerreros vencen! La victoria será para mi", pregunta62));
		this.getRespuestaDAO().create(new Respuesta(235, false, "¡¡Choque!! Guerreros de 10.000.000.000 poderes", pregunta62));
		this.getRespuestaDAO().create(new Respuesta(236, true, "¡¡Arde!! Super batalla feroz, extrema y ardiente", pregunta63));
		this.getRespuestaDAO().create(new Respuesta(237, false, "¡El renacer de la fusión! Goku y Vegeta", pregunta63));
		this.getRespuestaDAO().create(new Respuesta(238, false, "¡Explota el golpe del dragón! Si Goku no lo logra ¿quién lo hará?", pregunta63));
		this.getRespuestaDAO().create(new Respuesta(239, false, "¡Los Super guerreros vencen! La victoria será para mi", pregunta63));
		this.getRespuestaDAO().create(new Respuesta(240, false, "¡¡Choque!! Guerreros de 10.000.000.000 poderes", pregunta64));
		this.getRespuestaDAO().create(new Respuesta(241, true, "¡¡La galaxia está en peligro!! Un guerrero Súper increíble", pregunta64));
		this.getRespuestaDAO().create(new Respuesta(242, false, "¡Explota el golpe del dragón! Si Goku no lo logra ¿quién lo hará?", pregunta64));
		this.getRespuestaDAO().create(new Respuesta(243, false, "El hombre más fuerte de este mundo", pregunta64));
		this.getRespuestaDAO().create(new Respuesta(244, false, "El hombre más fuerte de este mundo", pregunta65));
		this.getRespuestaDAO().create(new Respuesta(245, true, "¡El renacer de la fusión! Goku y Vegeta", pregunta65));
		this.getRespuestaDAO().create(new Respuesta(246, false, "¡¡Batalla extrema!! Los Tres Grandes Super Saiyajin", pregunta65));
		this.getRespuestaDAO().create(new Respuesta(247, false, "Super batalla decisiva por el planeta Tierra", pregunta65));
		this.getRespuestaDAO().create(new Respuesta(248, false, "¡¡Choque!! Guerreros de 10.000.000.000 poderes", pregunta66));
		this.getRespuestaDAO().create(new Respuesta(249, true, "¡Explota el golpe del dragón! Si Goku no lo logra ¿quién lo hará?", pregunta66));
		this.getRespuestaDAO().create(new Respuesta(250, false, "El hombre más fuerte de este mundo", pregunta66));
		this.getRespuestaDAO().create(new Respuesta(251, false, "Super batalla decisiva por el planeta Tierra", pregunta66));
		this.getRespuestaDAO().create(new Respuesta(252, false, "¡¡Batalla extrema!! Los Tres Grandes Super Saiyajin", pregunta67));
		this.getRespuestaDAO().create(new Respuesta(253, false, "Super batalla decisiva por el planeta Tierra", pregunta67));
		this.getRespuestaDAO().create(new Respuesta(254, true, "¡Los dos en peligro! Los Súper guerreros nunca duermen", pregunta67));
		this.getRespuestaDAO().create(new Respuesta(255, false, "El hombre más fuerte de este mundo", pregunta67));
		this.getRespuestaDAO().create(new Respuesta(256, false, "¡¡Batalla extrema!! Los Tres Grandes Super Saiyajin", pregunta68));
		this.getRespuestaDAO().create(new Respuesta(257, false, "¡¡Choque!! Guerreros de 10.000.000.000 poderes", pregunta68));
		this.getRespuestaDAO().create(new Respuesta(258, true, "¡Los Super guerreros vencen! La victoria será para mi", pregunta68));
		this.getRespuestaDAO().create(new Respuesta(259, false, "¡El renacer de la fusión! Goku y Vegeta", pregunta68));
		this.getRespuestaDAO().create(new Respuesta(260, false, "Dragon Ball Z Budokai Tenkaichi", pregunta69));
		this.getRespuestaDAO().create(new Respuesta(261, false, "Dragon Ball Z Budokai 3", pregunta69));
		this.getRespuestaDAO().create(new Respuesta(262, false, "Dragon Ball Z Budokai", pregunta69));
		this.getRespuestaDAO().create(new Respuesta(263, true, "Dragon Ball Z Budokai 2", pregunta69));
		this.getRespuestaDAO().create(new Respuesta(264, false, "Dragon Ball Ranging Blast", pregunta70));
		this.getRespuestaDAO().create(new Respuesta(265, false, "Dragon Ball Ranging Blast 2", pregunta70));
		this.getRespuestaDAO().create(new Respuesta(266, false, "Dragon Ball Ultimate Tenkaichi", pregunta70));
		this.getRespuestaDAO().create(new Respuesta(267, true, "Dragon Ball Online", pregunta70));
		this.getRespuestaDAO().create(new Respuesta(268, false, "Dragon Ball El legado de Goku", pregunta71));
		this.getRespuestaDAO().create(new Respuesta(269, false, "Dragon Ball GT Transformations", pregunta71));
		this.getRespuestaDAO().create(new Respuesta(270, true, "Dragon Ball El legado de Goku II", pregunta71));
		this.getRespuestaDAO().create(new Respuesta(271, false, "Dragon Ball Buu's Fury", pregunta71));
		this.getRespuestaDAO().create(new Respuesta(272, true, "21º Tenkaichi Budokai", pregunta72));
		this.getRespuestaDAO().create(new Respuesta(273, false, "22º Tenkaichi Budokai", pregunta72));
		this.getRespuestaDAO().create(new Respuesta(274, false, "23º Tenkaichi Budokai", pregunta72));
		this.getRespuestaDAO().create(new Respuesta(275, false, "24º Tenkaichi Budokai", pregunta72));
		this.getRespuestaDAO().create(new Respuesta(276, false, "C8", pregunta73));
		this.getRespuestaDAO().create(new Respuesta(277, false, "C13", pregunta73));
		this.getRespuestaDAO().create(new Respuesta(278, false, "C14", pregunta73));
		this.getRespuestaDAO().create(new Respuesta(279, true, "C15", pregunta73));
		this.getRespuestaDAO().create(new Respuesta(280, false, "Era luchadora de la escuela de Mr. Satán", pregunta74));
		this.getRespuestaDAO().create(new Respuesta(281, true, "Era profesora de autoescuela", pregunta74));
		this.getRespuestaDAO().create(new Respuesta(282, false, "Era profesora del Orange High Star School", pregunta74));
		this.getRespuestaDAO().create(new Respuesta(283, false, "Con esta crisis estaba en paro", pregunta74));
		this.getRespuestaDAO().create(new Respuesta(284, false, "Buu +  Baby", pregunta75));
		this.getRespuestaDAO().create(new Respuesta(285, false, "Janemba + Buu", pregunta75));
		this.getRespuestaDAO().create(new Respuesta(286, false, "Cell + Buu", pregunta75));
		this.getRespuestaDAO().create(new Respuesta(287, true, "Janemba + Baby", pregunta75));
		this.getRespuestaDAO().create(new Respuesta(288, true, "Son Gokuh", pregunta76));
		this.getRespuestaDAO().create(new Respuesta(289, false, "Son Gohan", pregunta76));
		this.getRespuestaDAO().create(new Respuesta(290, false, "Son Goten", pregunta76));
		this.getRespuestaDAO().create(new Respuesta(291, false, "Gokuh Jr.", pregunta76));
		this.getRespuestaDAO().create(new Respuesta(292, false, "En la entrada al Otro Mundo", pregunta77));
		this.getRespuestaDAO().create(new Respuesta(293, true, "En el infierno", pregunta77));
		this.getRespuestaDAO().create(new Respuesta(294, false, "En el planeta de Kaioh Sama", pregunta77));
		this.getRespuestaDAO().create(new Respuesta(295, false, "En el planeta de los dioses Kaioh Shin", pregunta77));
		this.getRespuestaDAO().create(new Respuesta(296, false, "Bulma", pregunta78));
		this.getRespuestaDAO().create(new Respuesta(297, false, "Chichi", pregunta78));
		this.getRespuestaDAO().create(new Respuesta(298, true, "Lange", pregunta78));
		this.getRespuestaDAO().create(new Respuesta(299, false, "Pan", pregunta78));
		this.getRespuestaDAO().create(new Respuesta(300, false, "Kame Hame Ha", pregunta79));
		this.getRespuestaDAO().create(new Respuesta(301, false, "Shunkanido", pregunta79));
		this.getRespuestaDAO().create(new Respuesta(302, false, "Ma Sen Ko", pregunta79));
		this.getRespuestaDAO().create(new Respuesta(303, true, "Taiyoken", pregunta79));
		this.getRespuestaDAO().create(new Respuesta(304, true, "Goten y Trunks", pregunta80));
		this.getRespuestaDAO().create(new Respuesta(305, false, "Gokuh y Vegeta", pregunta80));
		this.getRespuestaDAO().create(new Respuesta(306, false, "Gokuh y Satán", pregunta80));
		this.getRespuestaDAO().create(new Respuesta(307, false, "Uub y Buu", pregunta80));
		this.getRespuestaDAO().create(new Respuesta(308, false, "Se ve explendido con ella", pregunta81));
		this.getRespuestaDAO().create(new Respuesta(309, true, "Un amante de la belleza como él odia este aspecto monstruoso", pregunta81));
		this.getRespuestaDAO().create(new Respuesta(310, false, "Le es indiferente", pregunta81));
		this.getRespuestaDAO().create(new Respuesta(311, false, "Le encanta demostrar esta forma monstruosa para intimidar", pregunta81));
		this.getRespuestaDAO().create(new Respuesta(312, false, "Frog", pregunta82));
		this.getRespuestaDAO().create(new Respuesta(313, false, "Cell", pregunta82));
		this.getRespuestaDAO().create(new Respuesta(314, true, "Gelto", pregunta82));
		this.getRespuestaDAO().create(new Respuesta(315, false, "Zarbon", pregunta82));
		this.getRespuestaDAO().create(new Respuesta(316, false, "Sargento", pregunta83));
		this.getRespuestaDAO().create(new Respuesta(317, false, "General", pregunta83));
		this.getRespuestaDAO().create(new Respuesta(318, false, "Soldado", pregunta83));
		this.getRespuestaDAO().create(new Respuesta(319, true, "Coronel", pregunta83));
		this.getRespuestaDAO().create(new Respuesta(320, true, "Serippa", pregunta84));
		this.getRespuestaDAO().create(new Respuesta(321, false, "Pan", pregunta84));
		this.getRespuestaDAO().create(new Respuesta(322, false, "Bra", pregunta84));
		this.getRespuestaDAO().create(new Respuesta(323, false, "Chichi", pregunta84));
		this.getRespuestaDAO().create(new Respuesta(324, false, "Son Gokuh", pregunta85));
		this.getRespuestaDAO().create(new Respuesta(325, true, "Son Gohan", pregunta85));
		this.getRespuestaDAO().create(new Respuesta(326, false, "Son Goten", pregunta85));
		this.getRespuestaDAO().create(new Respuesta(327, false, "Trunks", pregunta85));
		this.getRespuestaDAO().create(new Respuesta(328, false, "Vegeta + Gohan", pregunta86));
		this.getRespuestaDAO().create(new Respuesta(329, false, "Gokuh + Gohan", pregunta86));
		this.getRespuestaDAO().create(new Respuesta(330, true, "Vegeta + Kakarotto", pregunta86));
		this.getRespuestaDAO().create(new Respuesta(331, false, "Este personaje no es una fusión", pregunta86));
		this.getRespuestaDAO().create(new Respuesta(332, false, "Para resucitar a Bora, el padre de Upah", pregunta87));
		this.getRespuestaDAO().create(new Respuesta(333, false, "Para resucitar a todos los caídos en la batalla con Piccolo Daimaoh", pregunta87));
		this.getRespuestaDAO().create(new Respuesta(334, false, "Quería devolver a la vida a todas las víctimas de Vegeta", pregunta87));
		this.getRespuestaDAO().create(new Respuesta(335, true, "Quería devolver a la vida al ejercito de La Tierra, aniquilado por Cell", pregunta87));
		this.getRespuestaDAO().create(new Respuesta(336, true, "Trunks", pregunta88));
		this.getRespuestaDAO().create(new Respuesta(337, false, "Tapión", pregunta88));
		this.getRespuestaDAO().create(new Respuesta(338, false, "Son Goten", pregunta88));
		this.getRespuestaDAO().create(new Respuesta(339, false, "Son Gohan", pregunta88));
		this.getRespuestaDAO().create(new Respuesta(340, false, "Semifinalista", pregunta89));
		this.getRespuestaDAO().create(new Respuesta(341, false, "Finalista", pregunta89));
		this.getRespuestaDAO().create(new Respuesta(342, true, "Campeón", pregunta89));
		this.getRespuestaDAO().create(new Respuesta(343, false, "No participó", pregunta89));		
	}
	
	@Override
	public void close() {
		super.close();
		preguntaDAO = null;
		respuestaDAO = null;
	}

}